Adiciona o tipo de participação dinamicamente
womenwhocoderecife/wwcode-hacktoberfest-2020 pull request #128
Opened 2020-10-04 04:13 UTC by karenngomes

Atualmente, apenas o tipo 'Director' é exibido.

2020-10-04 13:35 UTC, simoneas02 requested changes
Verifica por favor o ajuste solicitado no comentário, qualquer dúvida pode usar o nosso Discord.

Abraços <3

2020-10-04 13:35 UTC, simoneas02 commented on src/components/Team/Session/index.js
> -              <Participation>Director</Participation>
Opa Karennn, massa tu ter feito essa melhoria, mas esses dados do objeto que tu criou já existem na propriedade title, tenta ajustar trocando **{PARTICIPATION[title] || 'Director'}** por **{title}** e sobe essa atualização, beijusss.

2020-10-05 04:15 UTC, karenngomes commented on src/components/Team/Session/index.js
> -              <Participation>Director</Participation>
Colocado sugestão de retirar o último caractere da string _title_ 😃

2020-10-05 16:08 UTC, merged

2020-10-05 16:09 UTC, simoneas02 commented
Vlws pela contribuição Girl 💯